### ISSUE TITLE
Not woking on Playnite 10.1

### ISSUE THREAD

**Issue by ppvnf** [Lacro59/playnite-howlongtobeat-plugin#164]
I just updated to the newest Playnite version (10.1) and noticed that this extension is no longer working. I would appreciate your help so I can keep using this extension in the newest Playnite version (unless it was integrated and I didn't notice).

![Captura de tela 2022-09-23 091653](https://user-images.githubusercontent.com/73800734/191958560-fecbb2ef-5e89-417f-b66c-7f3064bf46fb.png)

**Comment by GTWAnthony** [comment]
Im in a similar position, but it looks like 9.X is fixed, hopefully will see an update to make it compatible with 10.1

**Comment by BloodShed-Oni** [comment]
More like 10.2 by this time.

**Comment by kccricket** [comment]
```
25-09 11:49:28.762|ERROR|ExtensionFactory:Failed to load plugin: HowLongToBeat
25-09 11:49:28.762|ERROR|ExtensionFactory:
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Playnite.Plugins.ExtensionFactory.<LoadPlugins>d__33.MoveNext() in C:\projects\playnite\source\Playnite\Plugins\ExtensionFactory.cs:line 449
   at Playnite.Plugins.ExtensionFactory.LoadPlugins(List`1 ignoreList, Boolean builtInOnly, List`1 externals) in C:\projects\playnite\source\Playnite\Plugins\ExtensionFactory.cs:line 409
25-09 11:49:28.762|ERROR|ExtensionFactory:
System.TypeLoadException: Method 'BufferedUpdate' in type 'CommonPlayniteShared.Database.ItemCollection`1' from assembly 'HowLongToBeat, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
```

**Comment by kccricket** [comment]
I believe this is because this project is embedding the CommonPlayniteShared types, rather than referencing a library bundled with Playnite. The embedded ItemCollection type doesn't implement the methods added to IItemCollection in Playnite commit 3ad410738dc937f57036a41e5c7e011ccc092673. I briefly compared this project's references against how other plugins have theirs set up, but I'm not practiced enough with the .NET build system to make a recommendation.

**Comment by CloudGospel** [comment]
hope this works with the new update love this addon

**Comment by SquishyMochi514** [comment]
Yeah we are fixing it right now.

**Comment by ppvnf** [comment]
Thanks for fixing it!

https://github.com/Lacro59/playnite-howlongtobeat-plugin/releases/tag/v3.0
