### ISSUE TITLE
No submit data find for x

### ISSUE THREAD

**Issue by JustThat70** [Lacro59/playnite-howlongtobeat-plugin#186]
Some games are throwing errors when trying to upload playtime, manually or automatically. For example, Dark Souls Remastered:

17-06 19:04:03.339|INFO |HowLongToBeat#HowLongToBeatClient:GetSubmitData(Dark Souls: Remastered, 28149882)
17-06 19:04:03.838|ERROR|HowLongToBeat#Common:Error on GetSubmitData()|D:\GitHub\Lacro59\playnite-howlongtobeat-plugin\source\Services\HowLongToBeatClient.cs|488
System.Exception: No submit data find for Dark Souls: Remastered - 28149882
   at HowLongToBeat.Services.HowLongToBeatClient.GetSubmitData(String GameName, String UserGameId) in D:\GitHub\Lacro59\playnite-howlongtobeat-plugin\source\Services\HowLongToBeatClient.cs:line 488
17-06 19:04:03.838|WARN |HowLongToBeat#PluginDatabaseObject`4:No hltbPostData for Dark Souls: Remastered

**Comment by Sergiokool** [comment]
Same problem here various games doing me the same, the extension must be fixed please 🙄

**Comment by BloodShed-Oni** [comment]
Also seemingly random games here (they worked before)

Log for Yu-Gi-Oh! Duel Links
```
18-06 13:16:34.016|INFO |HowLongToBeat#HowLongToBeatClient:GetSubmitData(Yu-Gi-Oh! Duel Links, 24159304)
18-06 13:16:34.941|ERROR|HowLongToBeat#Common:Error on GetSubmitData()|D:\GitHub\Lacro59\playnite-howlongtobeat-plugin\source\Services\HowLongToBeatClient.cs|488
System.Exception: No submit data find for Yu-Gi-Oh! Duel Links - 24159304
   at HowLongToBeat.Services.HowLongToBeatClient.GetSubmitData(String GameName, String UserGameId) in D:\GitHub\Lacro59\playnite-howlongtobeat-plugin\source\Services\HowLongToBeatClient.cs:line 488
18-06 13:16:34.941|WARN |HowLongToBeat#PluginDatabaseObject`4:No hltbPostData for Yu-Gi-Oh! Duel Links
```
