### ISSUE TITLE
ExtensionFactory:Failed to load plugin: HowLongToBeat

### ISSUE THREAD

**Issue by Gygun** [Lacro59/playnite-howlongtobeat-plugin#61]
Error log (v1.2.1):
`27-12 11:22:53.297|ERROR|ExtensionFactory:Failed to load plugin: HowLongToBeat
27-12 11:22:53.297|ERROR|ExtensionFactory:
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at Playnite.Plugins.ExtensionFactory.<LoadPlugins>d__42.MoveNext() in E:\Devel\Playnite\source\Playnite\Plugins\ExtensionFactory.cs:line 384
   at Playnite.Plugins.ExtensionFactory.LoadPlugins(IPlayniteAPI injectingApi, List 1 ignoreList, Boolean builtInOnly) in E:\Devel\Playnite\source\Playnite\Plugins\ExtensionFactory.cs:line 342`

It's happening to other plugins as well (localization, game activity, success story). 1.0/1.1 versions works fine, but when I update to 1.2, it failed to load. Any ideas what could I try? Thanks!

This versions works for me: [https://puu.sh/H1lve/5c88a8fe0c.png](https://puu.sh/H1lve/5c88a8fe0c.png)

**Comment by Lacro59** [comment]
Is there the same issue with v1.2.2?

**Comment by Gygun** [comment]
They work now, except for this one:  
`12-01 07:27:28.906|ERROR|ExtensionFactory:Failed to load plugin: CheckLocalizations
System.NullReferenceException: Object reference not set to an instance of an object.
   at CheckLocalizations.CheckLocalizationsSettings..ctor(CheckLocalizations plugin) in H:\GitHub\Lacro59\playnite-checklocalizations-plugin\CheckLocalizationsSettings.cs:line 59
   at CheckLocalizations.CheckLocalizations..ctor(IPlayniteAPI api) in H:\GitHub\Lacro59\playnite-checklocalizations-plugin\CheckLocalizations.cs:line 39`

Do you want me to open a issue there? Thanks for fixing the rest!

**Comment by Lacro59** [comment]
Yes, you can.
Thanks.
