### ISSUE TITLE
[Error] Database Error

### ISSUE THREAD

**Issue by JourneyOver** [Lacro59/playnite-howlongtobeat-plugin#66]
```
06-02 09:45:08.427|ERROR|Common:HowLongToBeat [H:\GitHub\Lacro59\playnite-howlongtobeat-plugin\HowLongToBeat.cs 121] - Error to load game data for DOOM Eternal
System.NullReferenceException: Object reference not set to an instance of an object.
   at HowLongToBeat.Services.HowLongToBeatDatabase.<>c__DisplayClass10_0.<GetUserHltbData>b__0(TitleList x) in H:\GitHub\Lacro59\playnite-howlongtobeat-plugin\Services\HowLongToBeatDatabase.cs:line 536
   at System.Collections.Generic.List`1.Find(Predicate`1 match)
   at HowLongToBeat.Services.HowLongToBeatDatabase.GetUserHltbData(Int32 HltbId) in H:\GitHub\Lacro59\playnite-howlongtobeat-plugin\Services\HowLongToBeatDatabase.cs:line 536
   at HowLongToBeat.Views.HowLongToBeatView..ctor(IPlayniteAPI PlayniteApi, HowLongToBeatSettings settings, GameHowLongToBeat gameHowLongToBeat) in H:\GitHub\Lacro59\playnite-howlongtobeat-plugin\Views\HowLongToBeatView.xaml.cs:line 74
   at HowLongToBeat.HowLongToBeat.<>c__DisplayClass17_0.<GetGameMenuItems>b__0(GameMenuItemActionArgs gameMenuItem) in H:\GitHub\Lacro59\playnite-howlongtobeat-plugin\HowLongToBeat.cs:line 121
```

After authenticating myself through HLTB plugin settings this seems to happen for pretty much any and all games when clicking on "View HowLongtoBeat game data", I've tried resetting the database as well and doing a delete data on the games and neither seem to fix the issue after doing the initial data download of any games. This is running update v1.4.1, even tried downgrading to v1.4 and it was doing the same thing. If I delete the settings and don't authenticate myself at all the error goes away and I can view the game data.

I'll be making another error report that is happening as well right after this that has to do with trying to view user data and not game data, though I'm sure that fixing this issue will hopefully fix the other issue as well..

Edit: This error does not seem to appear in v1.3, only v1.4 and v1.4.1 so far.

Edit2: Here is just a log with just everything. 
[playnite.log](https://github.com/Lacro59/playnite-howlongtobeat-plugin/files/5937457/playnite.log)

Edit3: more information on a clean version of playnite after setting up my extensions and stuff again that happens while running through user authentication not sure if to put this in #67 or here so I'm just going to post it here (this never shown up in my old playnite runs):
```
06-02 12:48:58.749|ERROR|Common:HowLongToBeat [H:\GitHub\Lacro59\playnite-howlongtobeat-plugin\Services\HowLongToBeatClient.cs 626] - Error on GetTitleList()
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: index
   at AngleSharp.Extensions.CollectionExtensions.GetItemByIndex[T](IEnumerable`1 items, Int32 index)
   at AngleSharp.Dom.Collections.HtmlCollection`1.get_Item(Int32 index)
   at HowLongToBeat.Services.HowLongToBeatClient.GetTitleList(IElement element) in H:\GitHub\Lacro59\playnite-howlongtobeat-plugin\Services\HowLongToBeatClient.cs:line 626
```

**Comment by JourneyOver** [comment]
As noted in #67, I completely reset my HLTB profile by removing all games from my `playthroughs` list, and now this is error seems to no longer be happening on 1.4.1. As mentioned in other issue, I can't test in 1.4.2 due to #68

**Comment by JourneyOver** [comment]
Continues to work correctly in 1.4.3, still not sure what was on my hltb profile that was causing this issue..

If you want to take a look I have a .cvs export with all my previous games from before I purged my profile, could possibly help narrow down what game(s) had caused it.
[HLTB_Games_2021-02-07.csv.txt](https://github.com/Lacro59/playnite-howlongtobeat-plugin/files/5943883/HLTB_Games_2021-02-07.csv.txt) (had to put .txt on it so that github would allow me to upload it)

**Comment by Lacro59** [comment]
If you try the Playnite 9 beta, can you check with the v2.0?
