### ISSUE TITLE
[Error] Failed to compare two elements in the array.

### ISSUE THREAD

**Issue by JourneyOver** [Lacro59/playnite-howlongtobeat-plugin#67]
```
06-02 10:02:37.632|ERROR|MainMenu:Main menu extension action failed.
System.InvalidOperationException: Failed to compare two elements in the array. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at HowLongToBeat.Views.HowLongToBeatUserView.<>c.<.ctor>b__5_0(TitleList x, TitleList y) in H:\GitHub\Lacro59\playnite-howlongtobeat-plugin\Views\HowLongToBeatUserView.xaml.cs:line 47
   at System.Array.FunctorComparer`1.Compare(T x, T y)
   at System.Collections.Generic.ArraySortHelper`1.PickPivotAndPartition(T[] keys, Int32 lo, Int32 hi, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(T[] keys, Int32 lo, Int32 hi, Int32 depthLimit, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(T[] keys, Int32 left, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Comparison`1 comparison)
   at HowLongToBeat.Views.HowLongToBeatUserView..ctor() in H:\GitHub\Lacro59\playnite-howlongtobeat-plugin\Views\HowLongToBeatUserView.xaml.cs:line 47
   at HowLongToBeat.HowLongToBeat.<GetMainMenuItems>b__18_0(MainMenuItemActionArgs mainMenuItem) in H:\GitHub\Lacro59\playnite-howlongtobeat-plugin\HowLongToBeat.cs:line 178
   at Playnite.DesktopApp.Controls.MainMenu.<>c__DisplayClass14_2.<AddExtensionItems>b__1(Object _, RoutedEventArgs __) in E:\Devel\Playnite\source\Playnite.DesktopApp\Controls\MainMenu.cs:line 358
```

same deal with #66 after authentication and trying to view user data on a game it throws the above error message, along with the above stuff in the playnite.log, have tried the same stuff I have mentioned in my previous issue thread.

Edit: The error appears in v1.3 unlike how #66 stopped throwing errors in v1.3 but it seems to be a slightly different error (not sure if it is worth posting or not but I will as a good measure):
```
06-02 10:14:41.972|ERROR|MainMenu:Main menu extension action failed.
System.NullReferenceException: Object reference not set to an instance of an object.
   at HowLongToBeat.Views.HowLongToBeatUserView..ctor() in H:\GitHub\Lacro59\playnite-howlongtobeat-plugin\Views\HowLongToBeatUserView.xaml.cs:line 47
   at HowLongToBeat.HowLongToBeat.<GetMainMenuItems>b__18_0(MainMenuItemActionArgs mainMenuItem) in H:\GitHub\Lacro59\playnite-howlongtobeat-plugin\HowLongToBeat.cs:line 178
   at Playnite.DesktopApp.Controls.MainMenu.<>c__DisplayClass14_2.<AddExtensionItems>b__1(Object _, RoutedEventArgs __) in E:\Devel\Playnite\source\Playnite.DesktopApp\Controls\MainMenu.cs:line 358
```

**Comment by JourneyOver** [comment]
Still not fully sure what actually caused this problem, but I completely reset my HLTB profile by removing pretty much every single game from my `playthroughs` lists and then it started working on 1.4.1 without throwing an error, I'm not able to test on 1.4.2 due to the #68

Doing a complete reset of my HLTB profile seems to have fixed #66 as well..

**Comment by JourneyOver** [comment]
Same deal with #66 . seems to work correctly still in 1.4.3. Left a cvs of my games before the purge in #66 if you want to take a look, could help narrow down what had caused it.

**Comment by Lacro59** [comment]
If you try the Playnite 9 beta, can you check with the v2.0?

**Comment by JourneyOver** [comment]
tbh I haven't messed with playnite in a long time, but I'll check this out and #66 when I get a chance.
